"""Build Sources/data.js from the question bank, translations and vocabulary.

Inputs (Tools/data):
  qa.json      237 questions parsed from the official oral question bank (114年11月 version)
  tr*.json     English translations, short spoken answers and tips, keyed by question id
  vocab.json   curated civic/legal vocabulary

Usage:
  pip install pypinyin
  python3 Tools/build_data.py
"""
import glob
import json
import os
import re

from pypinyin import Style, load_phrases_dict, load_single_dict, pinyin

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR = os.path.join(ROOT, 'Tools', 'data')
OUT = os.path.join(ROOT, 'Sources', 'data.js')

# Taiwan readings that differ from the mainland defaults
load_phrases_dict({'垃圾': [['lè'], ['sè']], '星期': [['xīng'], ['qí']]})
load_single_dict({ord('期'): 'qí'})

HAN = re.compile(r'[㐀-鿿]')

CATS = [
    ('題型', 'Question patterns'),
    ('政府組織類', 'Government organization'), ('國旗類', 'National flag'), ('參政權類', 'Political rights'),
    ('一般法律類', 'General law'), ('簽證及護照類', 'Visas & passports'), ('居留類', 'Residence'),
    ('歸化類', 'Naturalization'), ('戶籍類', 'Household registration'), ('教育類', 'Education'),
    ('財稅金融類', 'Tax & finance'), ('兵役類', 'Military service'), ('社會福利類', 'Social welfare'),
    ('家庭暴力防治類', 'Domestic violence prevention'), ('地政類', 'Land administration'),
    ('全民健保及醫療類', 'Health insurance & medical'), ('就業類', 'Employment'), ('交通安全類', 'Traffic safety'),
    ('環境保護類', 'Environmental protection'), ('災害防治類', 'Disaster prevention'),
    ('消費者保護類', 'Consumer protection'), ('自然環境及原住民類', 'Nature & Indigenous peoples'),
    ('民俗節慶類', 'Festivals & customs'), ('日常生活類', 'Daily life'),
]


def py_arr(s):
    """One pinyin syllable per character ('' for non-hanzi); hanzi runs keep phrase context."""
    arr = []
    for m in re.finditer(r'[㐀-鿿]+|[^㐀-鿿]+', s):
        seg = m.group(0)
        if HAN.match(seg[0]):
            arr += [p[0] for p in pinyin(seg, style=Style.TONE)]
        else:
            arr += [''] * len(seg)
    assert len(arr) == len(s)
    return arr


def load(name):
    with open(os.path.join(DATA_DIR, name), encoding='utf-8') as f:
        return json.load(f)


def main():
    qa = {i['id']: i for i in load('qa.json')}
    tr = {}
    for path in sorted(glob.glob(os.path.join(DATA_DIR, 'tr*.json'))):
        with open(path, encoding='utf-8') as f:
            for t in json.load(f):
                tr[t['id']] = t
    missing = sorted(set(qa) - set(tr))
    assert not missing, f'missing translations: {missing}'

    qs = []
    for i in sorted(qa):
        q, t = qa[i], tr[i]
        key = t['key'].rstrip('。')
        qs.append({
            'id': i, 'cat': q['cat'], 'q': q['q'], 'a': q['a'],
            'qp': py_arr(q['q']), 'ap': py_arr(q['a']), 'key': key, 'kp': py_arr(key),
            'qe': t['q_en'], 'ae': t['a_en'], 'ke': t['key_en'],
            'tip': t.get('tip') or '', 'own': bool(t.get('own')),
        })

    vocab = []
    for v in load('vocab.json'):
        ids = [i for i in sorted(qa) if v['zh'] in qa[i]['q'] + qa[i]['a']]
        if ids:
            vocab.append({'zh': v['zh'], 'pa': py_arr(v['zh']), 'p': ' '.join(p for p in py_arr(v['zh']) if p),
                          'en': v['en'], 'cat': v['cat'], 'ids': ids})

    data = {'version': '114年11月 (Nov 2025)', 'cats': [{'zh': z, 'en': e} for z, e in CATS], 'qs': qs, 'vocab': vocab}
    with open(OUT, 'w', encoding='utf-8') as f:
        f.write('// Generated by Tools/build_data.py. Do not edit by hand.\n')
        f.write('window.DATA = ' + json.dumps(data, ensure_ascii=False, separators=(',', ':')) + ';\n')
    print(f'{len(qs)} questions, {len(vocab)} words -> {os.path.relpath(OUT, ROOT)}')


if __name__ == '__main__':
    main()
